export const PROVIDER_IDS = [
    'zenn-ai',
    'zenn-llm',
    'qiita-ai',
    'qiita-llm',
    'geeknews',
    'aitimes',
    'yozm',
    'naver-d2',
    'kakaotech',
    'itmedia',
    'publickey',
    'hatena-it',
    'openai',
    'anthropic',
    'huggingface',
    'deepmind',
    'google-research',
    'simon-willison',
    'raschka',
    'marktechpost',
] as const
